name: 0.2.$(Rev:r)

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - infrastructure/stages/kubernetes-prd
      - infrastructure/azure-pipelines.kubernetes-prd.yml

pr:
  autoCancel: true
  drafts: true
  branches:
    include:
      - main

variables:
  - template: '../pipeline-templates/infrastructure-variables.yml'
  - name: projectFolder
    value: infrastructure/stages/kubernetes-prd

stages:
  - template: '../pipeline-templates/kubernetes-plan.yml'
    parameters:
      projectFolder: $(projectFolder)
      stateBlobName: kubernetes-prd.terraform.tfstate

  - template: '../pipeline-templates/kubernetes-deploy.yml'
    parameters:
      environment: kubernetes-prd
      projectFolder: $(projectFolder)
