name: 0.2.$(Rev:r)

resources:
  pipelines:
    - pipeline: build
      source: 'captainkube-docker'
      trigger: true
      branch: main
    - pipeline: helm
      source: 'captainkube-chart'
      trigger: true
      branch: main

trigger:
  batch: true
  paths:
    include:
      - captainkube/azure-pipelines.deploy.yaml
  branches:
    include:
      - main

variables:
  - group: acr
  - group: azure-env
  - name: containerRepository
    value: captainkube
  - name: imageTag
    value: $(resources.pipeline.build.runName)
  - name: chartTag
    value: $(resources.pipeline.helm.runName)
  - name: HELM_EXPERIMENTAL_OCI
    value: 1
  - name: namespace
    value: charts

stages:
  - template: '../pipeline-templates/helm-deployment.yml'
    parameters:
      environment: dev.apps
      kubernetesCluster: aks-$(AZURE_ENV_INSTANCE_ID)-dev

  - template: '../pipeline-templates/helm-deployment.yml'
    parameters:
      environment: prd.apps
      kubernetesCluster: aks-$(AZURE_ENV_INSTANCE_ID)-prd
